version: 2

models:
    - name: stg_tpch_orders
      description: staging orders
      columns:
          - name: order_key
            description: primary key
            tests:
              - unique
              - not_null
          - name: status
            description: "{{ doc('status_code') }}"    
    - name: stg_tpch_line_items
      description: staging line items
      columns:
          - name: order_item_key
            description: primary key
            tests:
              - unique
              - not_null